//  script — fills the Seeddatabase with initial data
// Run with: npx prisma db seed
//
// What this does:
// 1. Creates the admin user
// 2. Inserts all static products from data/products.ts into PostgreSQL

import 'dotenv/config';
import { PrismaClient } from '../app/generated/prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { hash } from 'bcryptjs';

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const staticProducts = [
  {
    id: '1',
    name: 'iPhone 13 Pro',
    brand: 'Apple',
    category: 'smartphones' as const,
    price: 43999,
    oldPrice: 48999,
    emoji: '📱',
    image: 'https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp',
    badge: 'new' as const,
    colors: ['#8a8a8a', '#2d2926', '#4a5d52', '#c9c0b1'],
    specs: ['Чіп A15 Bionic', 'Камера Pro 12 МП', 'Дисплей Super Retina XDR', 'Face ID'],
    description: 'Флагманський iPhone 13 Pro з чіпом A15 Bionic, потрійною камерою Pro 12 МП та дисплеєм Super Retina XDR з ProMotion.',
    inStock: true,
    rating: 4,
    reviewCount: 156,
  },
  {
    id: '2',
    name: 'iPhone X',
    brand: 'Apple',
    category: 'smartphones' as const,
    price: 35999,
    oldPrice: 43999,
    emoji: '📱',
    image: 'https://cdn.dummyjson.com/product-images/smartphones/iphone-x/thumbnail.webp',
    badge: 'sale' as const,
    colors: ['#1d1d1d', '#c0c0c0'],
    specs: ['Дисплей Super Retina OLED 5.8"', 'Face ID', 'Подвійна камера 12 МП', 'Бездротова зарядка'],
    description: 'Перший iPhone з безрамковим OLED-дисплеєм та технологією розпізнавання обличчя Face ID.',
    inStock: true,
    rating: 3,
    reviewCount: 98,
  },
  {
    id: '3',
    name: 'Samsung Galaxy S10',
    brand: 'Samsung',
    category: 'smartphones' as const,
    price: 27999,
    oldPrice: 29999,
    emoji: '📱',
    image: 'https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s10/thumbnail.webp',
    badge: 'sale' as const,
    colors: ['#1d1d1d', '#e8e8e8', '#5a6b7a'],
    specs: ['Dynamic AMOLED дисплей', 'Потрійна камера', 'Сканер відбитків в екрані', '128 ГБ пам\'яті'],
    description: 'Флагман Samsung з динамічним AMOLED дисплеєм, потрійною камерою та сканером відбитків пальців під екраном.',
    inStock: true,
    rating: 3,
    reviewCount: 120,
  },
  {
    id: '4',
    name: 'Oppo F19 Pro Plus',
    brand: 'Oppo',
    category: 'smartphones' as const,
    price: 15999,
    oldPrice: 18999,
    emoji: '📱',
    image: 'https://cdn.dummyjson.com/product-images/smartphones/oppo-f19-pro-plus/thumbnail.webp',
    badge: 'sale' as const,
    colors: ['#1d1d1d', '#4a90d9'],
    specs: ['AMOLED дисплей 90 Гц', 'Потрійна камера 48 МП', '4310 мАг батарея', 'Швидка зарядка 50W'],
    description: 'Смартфон з акцентом на камеру: потрійний модуль 48 МП та яскравий AMOLED дисплей з частотою 90 Гц.',
    inStock: true,
    rating: 4,
    reviewCount: 64,
  },
  {
    id: '5',
    name: 'Realme XT',
    brand: 'Realme',
    category: 'smartphones' as const,
    price: 13999,
    emoji: '📱',
    image: 'https://cdn.dummyjson.com/product-images/smartphones/realme-xt/thumbnail.webp',
    badge: 'hit' as const,
    colors: ['#1d1d1d', '#e0c8a0'],
    specs: ['Камера 64 МП', 'Snapdragon 712', 'AMOLED дисплей', '4000 мАг батарея'],
    description: 'Смартфон з 64 МП камерою та потужним процесором Snapdragon 712 для відмінних фото та продуктивності.',
    inStock: true,
    rating: 5,
    reviewCount: 88,
  },
  {
    id: '6',
    name: 'MacBook Pro 14" Space Grey',
    brand: 'Apple',
    category: 'laptops' as const,
    price: 79999,
    emoji: '💻',
    image: 'https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/thumbnail.webp',
    badge: 'new' as const,
    colors: ['#4a4a4a', '#c0c0c0'],
    specs: ['Чіп Apple M1 Pro', 'Дисплей Liquid Retina XDR', '14"', 'До 17 год батареї'],
    description: 'Потужний MacBook Pro з чіпом M1 Pro та дисплеєм Liquid Retina XDR для професійної роботи.',
    inStock: true,
    rating: 4,
    reviewCount: 110,
  },
  {
    id: '7',
    name: 'Asus Zenbook Pro Dual Screen',
    brand: 'Asus',
    category: 'laptops' as const,
    price: 71999,
    oldPrice: 79999,
    emoji: '💻',
    image: 'https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/thumbnail.webp',
    badge: 'sale' as const,
    colors: ['#1d1d1d'],
    specs: ['Два дисплеї ScreenPad Plus', 'Intel Core i9', 'OLED 4K', '32 ГБ RAM'],
    description: 'Ноутбук із додатковим дисплеєм ScreenPad Plus для багатозадачності та продуктивності.',
    inStock: true,
    rating: 4,
    reviewCount: 52,
  },
  {
    id: '8',
    name: 'Huawei Matebook X Pro',
    brand: 'Huawei',
    category: 'laptops' as const,
    price: 55999,
    emoji: '💻',
    image: 'https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/thumbnail.webp',
    badge: 'hit' as const,
    colors: ['#5a6b7a', '#1d1d1d'],
    specs: ['Сенсорний дисплей 3K', 'Intel Core i7', 'Алюмінієвий корпус', 'До 13 год батареї'],
    description: 'Тонкий та елегантний ноутбук із сенсорним дисплеєм 3K та преміальним металевим корпусом.',
    inStock: true,
    rating: 5,
    reviewCount: 140,
  },
  {
    id: '9',
    name: 'Dell XPS 13 9300',
    brand: 'Dell',
    category: 'laptops' as const,
    price: 59999,
    oldPrice: 67999,
    emoji: '💻',
    image: 'https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/thumbnail.webp',
    badge: 'sale' as const,
    colors: ['#c0c0c0', '#1d1d1d'],
    specs: ['Дисплей InfinityEdge', 'Intel Core i7', '512 ГБ SSD', '13.4"'],
    description: 'Компактний ноутбук із практично безрамковим дисплеєм InfinityEdge та високою продуктивністю.',
    inStock: true,
    rating: 3,
    reviewCount: 45,
  },
  {
    id: '10',
    name: 'Apple AirPods Max Silver',
    brand: 'Apple',
    category: 'headphones' as const,
    price: 21999,
    oldPrice: 24999,
    emoji: '🎧',
    image: 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp',
    badge: 'sale' as const,
    colors: ['#e8e8e8'],
    specs: ['Активне шумоподавлення', 'Adaptive EQ', 'Просторовий звук', 'До 20 год роботи'],
    description: 'Преміальні накладні навушники з активним шумоподавленням, Adaptive EQ та просторовим звуком.',
    inStock: true,
    rating: 3,
    reviewCount: 76,
  },
  {
    id: '11',
    name: 'Apple AirPods',
    brand: 'Apple',
    category: 'headphones' as const,
    price: 5199,
    emoji: '🎧',
    image: 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/thumbnail.webp',
    badge: 'new' as const,
    colors: ['#e8e8e8'],
    specs: ['Бездротове з\'єднання', 'Сенсорне керування', 'Інтеграція з Siri', 'Кейс для зарядки'],
    description: 'Бездротові навушники з простим підключенням, сенсорним керуванням та підтримкою Siri.',
    inStock: true,
    rating: 4,
    reviewCount: 210,
  },
  {
    id: '12',
    name: 'Beats Flex Wireless Earphones',
    brand: 'Beats',
    category: 'headphones' as const,
    price: 1999,
    emoji: '🎧',
    image: 'https://cdn.dummyjson.com/product-images/mobile-accessories/beats-flex-wireless-earphones/thumbnail.webp',
    badge: 'hit' as const,
    colors: ['#1d1d1d'],
    specs: ['Магнітні навушники', 'До 12 год батареї', 'Bluetooth', 'Швидка зарядка Fast Fuel'],
    description: 'Зручні бездротові навушники з магнітним кріпленням та до 12 годин автономної роботи.',
    inStock: true,
    rating: 4,
    reviewCount: 95,
  },
  {
    id: '13',
    name: 'Apple Watch Series 4 Gold',
    brand: 'Apple',
    category: 'watches' as const,
    price: 13999,
    oldPrice: 15999,
    emoji: '⌚',
    image: 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-watch-series-4-gold/thumbnail.webp',
    badge: 'sale' as const,
    colors: ['#d4a76a', '#c0c0c0'],
    specs: ['Моніторинг пульсу', 'Фітнес-трекер', 'Дисплей Retina', 'Водозахист'],
    description: 'Стильний смарт-годинник із моніторингом пульсу, фітнес-трекером та яскравим дисплеєм Retina.',
    inStock: true,
    rating: 3,
    reviewCount: 130,
  },
  {
    id: '14',
    name: 'Rolex Submariner Watch',
    brand: 'Rolex',
    category: 'watches' as const,
    price: 559999,
    emoji: '⌚',
    image: 'https://cdn.dummyjson.com/product-images/mens-watches/rolex-submariner-watch/thumbnail.webp',
    badge: 'new' as const,
    colors: ['#1d1d1d', '#c0c0c0'],
    specs: ['Водонепроникність 300м', 'Швейцарський механізм', 'Сталевий корпус', 'Класичний дизайн'],
    description: 'Легендарний дайвер-годинник з багатою історією, відомий своєю надійністю та водонепроникністю.',
    inStock: true,
    rating: 3,
    reviewCount: 24,
  },
  {
    id: '15',
    name: "Women's Wrist Watch",
    brand: 'Fashion Co.',
    category: 'watches' as const,
    price: 5199,
    oldPrice: 5999,
    emoji: '⌚',
    image: "https://cdn.dummyjson.com/product-images/womens-watches/women's-wrist-watch/thumbnail.webp",
    badge: 'sale' as const,
    colors: ['#d4a76a', '#1d1d1d'],
    specs: ['Шкіряний ремінець', 'Кварцовий механізм', 'Елегантний дизайн', 'Водозахист'],
    description: 'Універсальний та модний жіночий годинник з комфортним ремінцем та елегантним дизайном.',
    inStock: true,
    rating: 4,
    reviewCount: 58,
  },
  {
    id: '16',
    name: 'Samsung Galaxy Tab S8 Plus',
    brand: 'Samsung',
    category: 'accessories' as const,
    price: 23999,
    emoji: '📱',
    image: 'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s8-plus-grey/thumbnail.webp',
    badge: 'hit' as const,
    colors: ['#5a6b7a'],
    specs: ['AMOLED дисплей', 'Підтримка S Pen', 'Потужний процесор', 'Велика батарея'],
    description: 'Потужний Android-планшет з великим AMOLED дисплеєм та підтримкою стилуса S Pen.',
    inStock: true,
    rating: 5,
    reviewCount: 88,
  },
  {
    id: '17',
    name: 'Apple MagSafe Battery Pack',
    brand: 'Apple',
    category: 'accessories' as const,
    price: 3999,
    oldPrice: 4699,
    emoji: '🔋',
    image: 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/thumbnail.webp',
    badge: 'sale' as const,
    colors: ['#e8e8e8'],
    specs: ['Магнітне кріплення', 'Бездротова зарядка', 'Компактний розмір', 'Сумісність з MagSafe'],
    description: 'Портативний акумулятор з магнітним кріпленням для швидкої бездротової зарядки iPhone.',
    inStock: true,
    rating: 4,
    reviewCount: 62,
  },
  {
    id: '18',
    name: 'Amazon Echo Plus',
    brand: 'Amazon',
    category: 'accessories' as const,
    price: 3999,
    emoji: '🔊',
    image: 'https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/thumbnail.webp',
    badge: 'hit' as const,
    colors: ['#1d1d1d', '#e8e8e8'],
    specs: ['Голосовий помічник Alexa', 'Преміальний звук', 'Керування Smart Home', 'Вбудований хаб'],
    description: 'Розумна колонка з голосовим помічником Alexa, якісним звуком та вбудованим хабом для розумного дому.',
    inStock: true,
    rating: 5,
    reviewCount: 145,
  },
];

async function main() {
  console.log('🌱 Starting seed...');

  // Create admin user
  const adminPassword = await hash('admin123', 12);
  const admin = await prisma.user.upsert({
    where: { email: 'admin@techstore.ua' },
    update: {},
    create: {
      name: 'Адміністратор',
      email: 'admin@techstore.ua',
      password: adminPassword,
      isAdmin: true,
    },
  });
  console.log(`✅ Admin user: ${admin.email}`);

  // Insert products (upsert — safe to run multiple times)
  for (const p of staticProducts) {
    await prisma.product.upsert({
      where: { id: p.id },
      update: { ...p, isStatic: true },
      create: { ...p, isStatic: true },
    });
  }
  console.log(`✅ ${staticProducts.length} products seeded`);

  console.log('🎉 Seed complete!');
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
